name: Super-Linter

on: push

jobs:
  super-lint:
    name: Limit code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkou code
        uses: actions/checkout@2
      
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
